language: python
python:
  - "3.6"

sudo: false

git:
  depth: 5

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda
  - conda info -a
  - conda env create -f ease-dev.yml -n ease-env
  - source activate ease-env

script:
  - cd web_interface
  - ./manage.py test
  - cd ../
